name :Go CI -Multiple versions

on:
   push:
     branches: ["master"]
   pull_request:
     branches: ["master"]


jobs:
   build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.20","1.21","1.22"]

    steps:
        -name: Checkout code
        uses: actions/checkout@v4

        -name: Setup Go
         uses:actions/setup-go@v5
         with:
            go-version:$
            {{matrix.go-version}}

        -name: Display Go version
         run: go version

        -name: Build application
         run: go build./...

        -name: Test
         run : go test./...