name: Multiple Version  Go

on:
  push:
   branches:
     -main
     -master
  pull_request:
   branches:
     -main
     -master
jobs:
  build:
   runs-on: ubuntu-latest
  
   strategy:
     matrix:
      go-version: [ "1.22","1.23","stable" ]
      
   steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
       go-version:${{ matrix.go-version }}

    - name: Verify Go version
      run: go version

    - name: Download  dependencies
      run:  go mod Download

    - name: Build application
      run:  go build ./....

    - name: Run tests
      run:  go test ./... 


